### ISSUE TITLE
Load your purchases as a playlist?

### ISSUE THREAD

**Issue by cmdcolin** [greggparrish/bandcamp_tagplayer#1]
I don't know how possible this is and I don't know anything about bandcamp APIs but I would really enjoy being able to access my library of purchases in bandcamp as a playlist in MPD (I just started using cantata as a frontend in case that matters). I don't have much interest in downloading all my bandcamp library as mp3 as I have purchased some large discographies that are like varying quality, so they are interesting to sample but not worth downloading but I would love to stream it these files

Cheers

**Comment by greggparrish** [comment]
Hiya Colin.  I was thinking about doing something similar to create playlists from other users' purchases, and that would work for your own as well.  The official API, unfortunately, is limited mostly to sales data for musicians/labels so I've had to rely on webscraping, but user collections are more straightforward than tags.

I'll take a look and see what I can do.

**Comment by greggparrish** [comment]
Added user library functionality with --user.  Enjoy!
